## load required libraries
library(ggplot2)

## seed for reproducibility
set.seed(0405)

## Data generation

# The code below will produce a data.frame with 100 rows and 6 columns with
#  the following variables:

# age - Continuous variable. Represents age of individuals. Generated from
#   Normal(50, 10) distribution, which we assumed because the average animal
#   is 50 with a 100 year variance
# likes_sandwiches - Continuous variable bounded in [0,1]. Represents probability
#   of whether an individual likes sandwiches. Generated by assuming a logistic
#   function based on the `age` variable and with an  offset to ensure we
#   detect probability increasing as age increases
# is_bear - Logical variable. Represents which observations in our dataset are
#   bears. Generated as Bernoulli(0.3)
# likes_marmalade - Continuous variable bounded in [0,1]. Represents probability
#   of whether an individual likes maramalade. Generated by assuming a logistic
#   function based on the `is_bear` variable and with an offset and some random
#   noise.
# likes_marmalade_sandwiches - Continuous variable bounded in [0,1]. Represents
#   probability of an individual liking marmalade sandwiches, defined by multiplying
#   `likes_sandwiches` and `likes_marmalade`
# age50 - Character variable, either "Age>=50" if `age > 50`, else "Age<50".
#   We recommend using for visualisation only.
# bear - Character variable, either "Bear!" if `is_bear`, else "Human".
#   We recommend using for visualisation only.

age = rnorm(100, 50, 10)
likes_sandwiches = round(1 / (1 + exp(-age + 55)), 2)
is_bear = as.logical(rbinom(100, 1, 0.3))
likes_marmalade = round(1 / (1 + exp(-is_bear - rnorm(100, 1e-2) - 0.5)), 2)
likes_marmalade_sandwiches = likes_sandwiches * likes_marmalade
age50 = ifelse(age > 50, "Age>=50", "Age<50")
bear = ifelse(is_bear, "Bear!", "Human")

# create data.frame
df = data.frame(
  age, age50, likes_sandwiches, bear, likes_marmalade,
  likes_marmalade_sandwiches
)

# plot to check distributions as expected
ggplot(df, aes(x = likes_marmalade_sandwiches, color = age50, fill = bear)) +
  geom_density() +
  facet_grid(vars(age50), vars(bear)) +
  theme_bw()

# run logistic regression to confirm expected results
fit = glm(likes_marmalade_sandwiches > 0.5 ~ age + is_bear, binomial(link = "logit"))
fit
summary(fit)
